
fullnameOverride: iot-dnsmasq
image:
  registry: ""
  repository: "test"
  tag: "latest"
  pullPolicy: "IfNotPresent"

network:
  # the interface name which communicate with edge node
  interface:
  # the ip address which communicate with edge node
  ip:

dns:
  enable: true

tftp:
  enable: true

dhcp:
  range_min:
  range_max:

tink_domain: ""

