
fullnameOverride: iot-dnsmasq
image:
  registry: ""
  repository: "test"
  tag: "latest"
  pullPolicy: "IfNotPresent"

namespace: default

network:
  # the interface name which communicate with edge node
  interface: "eno2"
  # the range for dhcp server.eg: 10.43.100.1,10.43.100.100
  dhcp_range: "10.43.100.210,10.43.100.250"
  gateway: "10.43.100.200"
  broadcast_ip: "10.43.100.255"

tftp:
  enable: true

pxe_server: "10.43.100.200"

tink_domain: "tinkerbell-nginx.chip.test"

# true or false
only_tftp: false

k8s:
  # the ip address of kube-dns service
  # kubectl -n kube-system get svc kube-dns -o custom-columns=IP:.spec.clusterIP --no-headers
  kubedns: 10.43.0.10

dns:
  enable: true
  ip_address: "10.248.2.5"
  domains:
    - name: tinkerbell-nginx.chip.test
      value: 10.43.100.3
    - name: chip.test
      value:  10.43.100.2
    - name: rancher.chip.test
      value: 10.43.100.2
    - name: keycloak.chip.test
      value: 10.43.100.2
    - name: vault.chip.test
      value: 10.43.100.2
    - name: observability-ui.chip.test
      value: 10.43.100.2
    - name: observability-admin.chip.test
      value: 10.43.100.2
    - name: iaas.chip.test
      value: 10.43.100.2
    - name: infra.chip.test
      value: 10.43.100.2
    - name: update.chip.test
      value: 10.43.100.2
    - name: web-ui.chip.test
      value: 10.43.100.2
    - name: api.chip.test
      value: 10.43.100.2
    - name: metadata.chip.test
      value: 10.43.100.2
    - name: registry.chip.test
      value: 10.43.100.2
    - name: registry-oci.chip.test
      value: 10.43.100.2
    - name: cluster-orch.chip.test
      value: 10.43.100.2
    - name: cluster-orch-edge-node.chip.test
      value: 10.43.100.2
    - name: infra-node.chip.test
      value: 10.43.100.2
    - name: logs-node.chip.test
      value: 10.43.100.2
    - name: metrics-node.chip.test
      value: 10.43.100.2
    - name: update-node.chip.test
      value: 10.43.100.2
    - name: app-orch.chip.test
      value: 10.43.100.2
    - name: fleet.chip.test
      value: 10.43.100.2
    - name: telemetry.chip.test
      value: 10.43.100.2
    - name: telemetry-node.chip.test
      value: 10.43.100.2
    - name: log-query.chip.test
      value: 10.43.100.2
    - name: app-service-proxy.chip.test
      value: 10.43.100.2
    - name: ws-app-service-proxy.chip.test
      value: 10.43.100.2
    - name: cluster-orch-node.chip.test
      value: 10.43.100.2
    - name: vnc.chip.test
      value: 10.43.100.2
    - name: release.chip.test
      value: 10.43.100.2
    - name: tinkerbell-server.chip.test
      value: 10.43.100.2
    - name: onboarding.chip.test
      value: 10.43.100.2
    - name: onboarding-node.chip.test
      value: 10.43.100.2
    - name: onboarding-stream.chip.test
      value: 10.43.100.2
    - name: fdo-mfg.chip.test
      value: 10.43.100.2
    - name: fdo-owner.chip.test
      value: 10.43.100.2
    - name: license-node.chip.test
      value: 10.43.100.2
    - name: orchestrator-license.chip.test
      value: 10.43.100.2
    - name: alerting-monitor.chip.test
      value: 10.43.100.2
    - name: argocd.chip.test
      value: 10.43.100.1
    
