
fullnameOverride: iot-dnsmasq
image:
  registry: ""
  repository: "test"
  tag: "latest"
  pullPolicy: "IfNotPresent"

namespace: default

network:
  # the interface name which communicate with edge node
  interface: eno8303

tftp:
  enable: true

# 10.248.2.5,114.114.114.114
remote_dns: 10.248.2.5,114.114.114.114

pxe_server: "10.67.100.173"

tink_domain: "tinkbell-nginx.zz-iotedge-domo.sh.intel.com"

# true or false
only_tftp: false

k8s:
  # the ip address of kube-dns service
  # kubectl -n kube-system get svc kube-dns -o custom-columns=IP:.spec.clusterIP --no-headers
  kubedns: 10.43.0.10

dns:
  enable: false
  domains:
    - name: tinkerbell-nginx.cluster.onprem
      value: 10.43.100.3
    - name: cluster.onprem
      value: 10.43.100.2
    - name: rancher.cluster.onprem
      value: 10.43.100.2
    - name: keycloak.cluster.onprem
      value: 10.43.100.2
    - name: vault.cluster.onprem
      value: 10.43.100.2
    - name: observability-ui.cluster.onprem
      value: 10.43.100.2
    - name: observability-admin.cluster.onprem
      value: 10.43.100.2
    - name: iaas.cluster.onprem
      value: 10.43.100.2
    - name: infra.cluster.onprem
      value: 10.43.100.2
    - name: update.cluster.onprem
      value: 10.43.100.2
    - name: web-ui.cluster.onprem
      value: 10.43.100.2
    - name: metadata.cluster.onprem
      value: 10.43.100.2
    - name: registry.cluster.onprem
      value: 10.43.100.2
    - name: cluster-orch.cluster.onprem
      value: 10.43.100.2
    - name: cluster-orch-edge-node.cluster.onprem
      value: 10.43.100.2
    - name: infra-node.cluster.onprem
      value: 10.43.100.2
    - name: logs-node.cluster.onprem
      value: 10.43.100.2
    - name: metrics-node.cluster.onprem
      value: 10.43.100.2
    - name: update-node.cluster.onprem
      value: 10.43.100.2
    - name: app-orch.cluster.onprem
      value: 10.43.100.2
    - name: fleet.cluster.onprem
      value: 10.43.100.2
    - name: telemetry.cluster.onprem
      value: 10.43.100.2
    - name: telemetry-node.cluster.onprem
      value: 10.43.100.2
    - name: log-query.cluster.onprem
      value: 10.43.100.2
    - name: app-service-proxy.cluster.onprem
      value: 10.43.100.2
    - name: ws-app-service-proxy.cluster.onprem
      value: 10.43.100.2
    - name: cluster-orch-node.cluster.onprem
      value: 10.43.100.2
    - name: vnc.cluster.onprem
      value: 10.43.100.2
    - name: release.cluster.onprem
      value: 10.43.100.2
    - name: gitea.cluster.onprem
      value: 10.43.100.2
    - name: tinkerbell-server.cluster.onprem
      value: 10.43.100.2
    - name: onboarding.cluster.onprem
      value: 10.43.100.2
    - name: onboarding-node.cluster.onprem
      value: 10.43.100.2
    - name: fdo-mfg.cluster.onprem
      value: 10.43.100.2
    - name: fdo-owner.cluster.onprem
      value: 10.43.100.2
    - name: license-node.cluster.onprem
      value: 10.43.100.2
    - name: argocd.cluster.onprem
      value: 10.43.100.1
