apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "iot-dnsmasq.fullname" . }}
  labels:
    {{- include "iot-dnsmasq.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      iotedge.intel.com/appname: dnsmasq
  replicas: 1
  template:
    metadata:
      labels:
        iotedge.intel.com/appname: dnsmasq
    spec:
      securityContext:
        runAsNonRoot: true
      hostNetwork: true
      hostIPC: true
      hostPID: true
      restartPolicy: Always
      containers:
        - name: dnsmasq
          image: {{ include "iot-dnsmasq.registry-url" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          {{- include "iot-dnsmasq.args" . | nindent 10 }}
          volumeMounts:
          - name: data
            mountPath: /home/iotedge/tftp
          securityContext:
            runAsUser: 1000
            capabilities:
              add: ["NET_ADMIN"]
      initContainers:
        - command:
          - timeout
          - 240h
          - sh
          - /scripts/script.sh
          name: wait4efi
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1000
          volumeMounts:
          - name: script-volume
            mountPath: /scripts
      volumes:
      - name: data
        emptyDir: {}
      - name: script-volume
        configMap:
          name: my-script
